In [38]:
import numpy as np
import math

# Metropolis-Hastings sampling

In [1]:
# Generate data points ... we will use beta distribution to create datapoints and then estimate those parameters using
# Metropolis-Hastings sampling

In [50]:
transition_model = lambda x: np.random.normal(x,[0.05,5],(2,))

In [51]:
transition_model((4,10))

array([ 3.9653823 , 12.56749924])

In [52]:
data_points = np.random.beta(5,30,1000)

In [53]:
len(data_points)

1000

In [54]:
data_points[0]

0.22685764695284397

In [55]:
# since a and b are positive we ensure that in the prior
def prior(w):
    if w[0]<=0 or w[1]<=0:
        return 0
    return 1

In [66]:
def transition_model(x):
    return np.random.normal(x,[0.5,5],(2,))

In [57]:
def likelihood(datapoints, a, b):
    l = lambda x:a*math.log(b)+(a-1)*math.log(x)-b*x-math.log(math.gamma(a))+math.log(prior((a,b)))
    val = [l(x) for x in datapoints]
    return sum(val)

In [76]:
def metropolisHastings(datapoints, iterations=1000):
    curr_parameter = (5,20)
    accepted_samples = []
    for _ in range(iterations):
        curr_likelihood = likelihood(datapoints, curr_parameter[0], curr_parameter[1])
        new_parameter = transition_model(curr_parameter)
        print(new_parameter)
        new_likelihood = likelihood(data_points, new_parameter[0], new_parameter[1])
        if new_likelihood>curr_likelihood:
            accepted_samples.append(new_parameter)
            curr_parameter = new_parameter
        else:
            x = np.random.normal(0,1)
            if x<math.exp(new_likelihood-curr_likelihood):
                accepted_samples.append(new_parameter)
                curr_parameter = new_parameter
    return accepted_samples            

In [78]:
accepted[-10:]

[array([ 6.55865537, 41.09166646]),
 array([ 6.03102656, 41.32720103]),
 array([ 5.06422276, 41.62022431]),
 array([ 4.52953836, 40.32903944]),
 array([ 3.73253777, 33.7567821 ]),
 array([ 3.91985081, 28.25886696]),
 array([ 4.56816843, 29.92500723]),
 array([ 4.70217036, 30.62106345]),
 array([ 4.59463376, 29.5337688 ]),
 array([ 5.27528581, 25.81391997])]