In [38]:
import numpy as np
import math

# Metropolis-Hastings sampling

In [1]:
# Generate data points ... we will use beta distribution to create datapoints and then estimate those parameters using
# Metropolis-Hastings sampling

In [50]:
transition_model = lambda x: np.random.normal(x,[0.05,5],(2,))

In [51]:
transition_model((4,10))

array([ 3.9653823 , 12.56749924])

In [52]:
data_points = np.random.beta(5,30,1000)

In [53]:
len(data_points)

1000

In [54]:
data_points[0]

0.22685764695284397

In [55]:
# since a and b are positive we ensure that in the prior
def prior(w):
    if w[0]<=0 or w[1]<=0:
        return 0
    return 1

In [66]:
def transition_model(x):
    return np.random.normal(x,[0.5,5],(2,))

In [57]:
def likelihood(datapoints, a, b):
    l = lambda x:a*math.log(b)+(a-1)*math.log(x)-b*x-math.log(math.gamma(a))+math.log(prior((a,b)))
    val = [l(x) for x in datapoints]
    return sum(val)

In [76]:
def metropolisHastings(datapoints, iterations=1000):
    curr_parameter = (5,20)
    accepted_samples = []
    for _ in range(iterations):
        curr_likelihood = likelihood(datapoints, curr_parameter[0], curr_parameter[1])
        new_parameter = transition_model(curr_parameter)
        print(new_parameter)
        new_likelihood = likelihood(data_points, new_parameter[0], new_parameter[1])
        if new_likelihood>curr_likelihood:
            accepted_samples.append(new_parameter)
            curr_parameter = new_parameter
        else:
            x = np.random.normal(0,1)
            if x<math.exp(new_likelihood-curr_likelihood):
                accepted_samples.append(new_parameter)
                curr_parameter = new_parameter
    return accepted_samples            

In [ ]:
accepted = metropolisHastings(data_points)

[ 5.63700826 18.66930578]
[ 4.59314492 26.14351929]
[ 4.40899351 28.03152444]
[ 4.1122589  25.45235171]
[ 3.58564855 29.98516488]
[ 4.58984263 22.32743672]
[ 3.51397075 28.0999218 ]
[ 4.00721533 19.77721364]
[ 3.40544788 17.95246861]
[ 3.78416296 19.58009313]
[ 3.62069799 11.66975173]
[2.87924756 3.1538419 ]
[ 4.19468089 13.29996913]
[ 4.92056796 13.4268201 ]
[4.08214744 6.15813823]
[4.20734073 9.15351197]
[3.64399914 5.44828087]
[3.40235628 5.91856843]
[3.96995024 9.62371452]
[3.90640259 7.02708735]
[4.39682213 9.60350401]
[ 3.11763387 16.27708621]
[ 2.8467829  16.16633817]
[ 3.26218092 20.43847279]
[ 3.48254745 19.66488596]
[ 3.34492281 19.89893657]
[ 3.17129267 20.24366323]
[ 3.56416064 15.94693039]
[ 3.47930836 26.61331356]
[ 3.36135528 25.95795594]
[ 3.5150282  35.27477551]
[ 3.13131322 37.20401182]
[ 3.85793976 41.70942736]
[ 3.72232912 32.59622602]
[ 3.73397542 34.77056991]
[ 3.02481464 43.64761591]
[ 3.76975447 37.94848573]
[ 4.0847689  25.15439536]
[ 4.52559926 30.06264432]
[ 

In [69]:
accepted[-10:]

[array([ 6.92754028, 28.73846895]),
 array([ 7.44965382, 35.48596891]),
 array([ 6.97072131, 40.37302157]),
 array([ 6.72961646, 41.25511454]),
 array([ 6.87545141, 42.61239254]),
 array([ 6.22712424, 40.69621347]),
 array([ 6.0551652 , 42.48770506]),
 array([ 6.6313063 , 48.21566878]),
 array([ 7.09728912, 47.98466057]),
 array([ 6.87038563, 46.28444622])]